#!/bin/sh

cd /home/pi

git clone https://github.com/myke239/sc-firmware-python.git


if [ -d "sc-firmware-python" ]; then
  cd sc-firmware-python

  chmod +x on_boot

  mv -r ./* ../

  rm -r sc-firmware-python
fi
